version: '3.8'

services:
  fourcut-diary-api-blue:
    image: ${FOURCUTDIARY_ECR_API_REPO}
    container_name: fourcut-diary-api-blue
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    restart: always
    networks:
      - fourcut-diary-network

  fourcut-diary-api-green:
    image: ${FOURCUTDIARY_ECR_API_REPO}
    container_name: fourcut-diary-api-green
    ports:
      - "8081:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    restart: always
    networks:
      - fourcut-diary-network

  fourcut-diary-notification:
    image: ${FOURCUTDIARY_ECR_NOTIFICATION_REPO}
    container_name: fourcut-diary-notification
    ports:
      - "8082:8082"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    restart: always
    networks:
      - fourcut-diary-network

networks:
  fourcut-diary-network:
    external: true
