version: '3.8'
services:
  playground-blue:
    image: ${FOURCUTDIARY_ECR_REPO}
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}

  playground-green:
    image: ${FOURCUTDIARY_ECR_REPO}
    expose:
      - 8080
    ports:
      - "8081:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}