FROM amd64/amazoncorretto:17

WORKDIR /app

COPY ./module-notification/build/libs/fourcut-diary-notification.jar /app/fourcut-diary-notification.jar

CMD ["java", "-Duser.timezone=Asia/Seoul", "-jar", "-Dspring.profiles.active=prod", "fourcut-diary-notification.jar"]
