
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: test
    username: test
    password: test
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

# auth
kakao:
  clientId: test
  redirectUri: test

apple:
  grant-type: test
  team-id: test
  client-id: test
  key-id: test
  audience: test
  private-key: test

# external
aws:
  lambda:
    region: test
    access-key: test
    secret-key: test